"""
Pydantic models for Agent Orchestrator system.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class Step(BaseModel):
    """Represents a single step in a plan."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    tool: str
    args: Dict[str, Any]
    description: Optional[str] = None


class Plan(BaseModel):
    """Represents an execution plan generated by the Planner."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    goal: str
    steps: List[Step]
    created_at: datetime = Field(default_factory=datetime.utcnow)


class RiskLevel(Enum):
    """Risk level classification for policy evaluation."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class PolicyResult(BaseModel):
    """Result of policy validation for a step."""

    allowed: bool
    reason: str = Field(default="")
    risk_level: RiskLevel = Field(default=RiskLevel.LOW)
    allowed_tools: List[str] = Field(default_factory=list)


class StepStatus(Enum):
    """Status of a step execution."""

    PENDING = "pending"
    EXECUTING = "executing"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"
    REJECTED = "rejected"


class StepResult(BaseModel):
    """Result of executing a single step."""

    step_id: str
    tool: str
    success: bool
    result: Optional[Any] = None
    error_message: Optional[str] = None
    status: StepStatus
    started_at: datetime
    completed_at: Optional[datetime] = None


class ExecutionStatus(Enum):
    """Status of an entire execution."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    STOPPED = "stopped"


class ExecutionResult(BaseModel):
    """Result of executing a plan."""

    execution_id: str = Field(default_factory=lambda: str(uuid4()))
    session_id: str
    goal: str
    status: ExecutionStatus
    results: List[StepResult] = Field(default_factory=list)
    error_message: Optional[str] = None
    completed_at: Optional[datetime] = None
    steps_executed: int = 0
    steps_max: int = 10


# Custom exceptions
class PolicyViolation(Exception):
    """Raised when a step violates policy rules."""

    def __init__(self, step: Step, reason: str):
        self.step = step
        self.reason = reason
        super().__init__(f"Policy violation for step '{step.tool}': {reason}")


class ToolExecutionError(Exception):
    """Raised when a tool fails to execute."""

    def __init__(self, tool: str, error: str):
        self.tool = tool
        self.error = error
        super().__init__(f"Tool '{tool}' execution failed: {error}")


class MaxStepsExceeded(Exception):
    """Raised when maximum steps limit is exceeded."""

    def __init__(self, max_steps: int):
        self.max_steps = max_steps
        super().__init__(f"Maximum steps limit ({max_steps}) exceeded")


class LLMError(Exception):
    """Raised when LLM call fails."""

    def __init__(self, message: str):
        super().__init__(f"LLM error: {message}")
